Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - bin/**/*
    - vendor/**/*

LineLength:
  Max: 120

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 26

Style/RegexpLiteral:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
