language: ruby
rvm:
 - 2.3.3
sudo: required
addons:
  chrome: stable
script:
 - 'bundle exec rspec'
 - 'bundle exec rubocop -S'

bundler_args: --without production

after_script:
  - bundle exec rake coveralls:push
