language: ruby
cache: bundler
rvm:
 - 2.3.3
sudo: false

addons:
  chrome: stable

script:
 - 'COVERAGE=true bundle exec rspec'
 - 'bundle exec rubocop -S'

bundler_args: --without production

after_script:
  - bundle exec rake coveralls:push
