default:
  image_caption: 'Photobooth'
  image_fontsize: 11
  font: 'Helvetica'
  font_color: '#1995AD'
  background_color: '#f1f1f2'
  combined_image_fontsize: 48

  # only implemented for emails currently
  locale: :en # available :en, :de

  # running on a raspi, live collage creation can slow things down
  # you can create them also in a batch: `rake picture_set:recreate_collage_images`
  render_collage: true

  # Turn this on if you have an email server available
  send_by_email: false

  mail_settings:
    from: 'no_reply@photobooth.com'
    address: ''
    port: 587
    user_name: ''
    password: ''
    authentication: 'plain'
    enable_starttls_auto: true


test:

  send_by_email: true
  render_collage: false
