default:
  image_caption: 'Photobooth'
  image_fontsize: 11
  font: 'LMMonoCaps10-Regular'
  font_color: '#1995AD'
  background_color: '#f1f1f2'
  combined_image_fontsize: 48
  locale: :de # available :en, :de

  mail_settings:
    from: ''
    address: ''
    port: 587
    user_name: ''
    password: ''
    authentication: 'plain'
    enable_starttls_auto: true

  dropbox:
    # raspi photobooth dropbox app:
    app_key: 123
    app_secret: 123
