default:
  image_caption: 'Photobooth'
  image_font: 'LMMonoCaps10-Regular'
  image_fontsize: 11

  combined_image_fontsize: 48
  background_color: '#f1f1f2'
  font_color: '#1995AD'

  dropbox:
    # raspi photobooth dropbox app:
    app_key: 123
    app_secret: 123
