name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  test:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby-version: ['4.0.5']

    steps:
    - uses: actions/checkout@v7

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Run style checks
      run: bundle exec rubocop -S

    - name: Run tests
      run: "COVERAGE=true bundle exec rspec"
